In [1]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

In [7]:
from alpha_vantage.alphavantage import AlphaVantage
from alpha_vantage.fundamentaldata import FundamentalData
from alpha_vantage.timeseries import TimeSeries
import numpy as np
import pandas as pd
from pandas import DataFrame as df, Timestamp
import csv
import requests
import os
import time
#import module for mysql 
from os import path
import mysql.connector as mysql
from pandas import DataFrame
from CalFundamental import calFund

def randomize () :
    global zkey
    global _API_KEY_TEST
    zkey += 1
    maxcounter = len(names) - 1
    if zkey > maxcounter :
        zkey = 0
    _API_KEY_TEST = names[zkey]
    print ("the API key right now is : "+_API_KEY_TEST)
    return _API_KEY_TEST

def connect(db_name):
    try:
        return mysql.connect(
            host='localhost',
            user='root',
            password='minyak23',
            database=db_name)
    except Error as e:
        print(e)
def step_1() :
    global step 
    step = "step_1"
    data1, meta_data = fd.get_income_statement_quarterly(entity)  #get income statement quarterly data
    data1.to_csv(r'C:\Varians\Income Statement Quarterly.csv', index=None, header=True)
    print("Succsesfully Pull Data 1 from web")
def step_2() :  
    global step 
    step = "step_2"
    data2, meta_data = fd.get_cash_flow_quarterly(entity) #get cash flow quarterly data
    data2.to_csv(r'C:\Varians\Cash Flow Quarterly.csv', index=None, header=True)
    print("Succsesfully Pull Data 2 from web")
def step_3():
    global step 
    step = "step_3"
    data3, meta_data = fd.get_balance_sheet_quarterly(entity) #get balance sheet quarterly data
    data3.to_csv(r'C:\Varians\Balance Sheet Quarterly.csv', index=None, header=True)
    print("Succsesfully Pull Data 3 from web")
def step_4():
    global step 
    step = "step_4"
    global OV
    fd = FundamentalData(key=_API_KEY_TEST, output_format='json')
    OV, meta_data = fd.get_company_overview( entity)
    split_OV=OV
    #write tuple/list overview to csv file
    with open(r'C:\Varians\Overview2.csv', 'w') as g:
        writer1=csv.writer(g,lineterminator='\n')
        writer1.writerow(split_OV.keys())
        writer1.writerow(split_OV.values())
        
    print("Succsesfully Pull Data Overview from web")
        
def step_5():
    global step 
    step = "step_5"
    ts = TimeSeries(key=_API_KEY_TEST, output_format='pandas')
    last_price, meta_data = ts.get_monthly(entity)
    last_price.to_csv(r'C:\Varians\Last Price.csv', index=True, header=True)
    print("Succsesfully Pull Data Timeseries from web")

if __name__ == "__main__":        
    # define the name of the directory to be created
    path = "/Varians"
    #creating folder on C:
    try:
        os.makedirs(path)
    except OSError:
        print ("Creation of the directory %s failed" % path)
    else:
        print ("Successfully created the directory %s" % path)

    with open(r'C:\Varians\stocklist.csv') as slist:
        stocklist = pd.read_csv(slist, header = None)

    stocklist = stocklist.rename(columns={0 : 'company', 1 : 'market', 2 : 'ticker'})
    stocklist.ticker = stocklist.ticker.str.strip()

    _API_KEY_TEST1 = 'G23MAAVKWB5TMPMV'
    _API_KEY_TEST2 = '6PE06AMZAM1MCGFX' #myanuarfirdaus
    _API_KEY_TEST3 = '6HZYCBP71FGOR1O5' #myanuarfirdaus23
    _API_KEY_TEST4 = 'X5LNMI2AESR1YQCU' #muh_yanuar_firdaus@yahoo.com
    _API_KEY_TEST5 = 'YBBKWRK4VSTP4GZH' #anggiengineer@yahoo.com
    _API_KEY_TEST6 = 'X3Z3LQ31Z9B1OYX9' #myanuarfirdaus@hotmail.com
    names = [_API_KEY_TEST1,_API_KEY_TEST2,_API_KEY_TEST3,_API_KEY_TEST4,_API_KEY_TEST5,_API_KEY_TEST6]
    # names = [_API_KEY_TEST4,_API_KEY_TEST5,_API_KEY_TEST6]

    for zticker in list (stocklist.ticker) :
        entity = str(zticker)
        print ("Stock Ticker Name : "+entity)
        _API_KEY_TEST = ""
        zkey = 0
        step = ""
        df_OV = pd.DataFrame()
        ISQ_reader = pd.DataFrame()
        CFQ_reader = pd.DataFrame()
        BSQ_reader = pd.DataFrame()
        dict_table = pd.DataFrame()

        randomize()

        #call data API Fundamental Quarterly
        fd = FundamentalData(key=_API_KEY_TEST, output_format='pandas')
        procedure = [step_1,step_2,step_3,step_4,step_5]

        while True :
            try : 
                for i in procedure :
                    i()
                Calculation, CFQ_reader, ISQ_reader, BSQ_reader = calFund()
                #preparing pandas dataframe to list inputing to mysql

                mysql_list = []
                Unique_ID  = []
                StockName  = [entity.upper()]*len(Calculation['Date'])  

                for i in range (len(Calculation['Date'])) :
                    temp = entity + str(Calculation['Date'][i].strftime('%Y%m%d'))
                    Unique_ID.append(temp)
                    i += 1

                mysql_list.append(Unique_ID)
                mysql_list.append(StockName)

                for i in list(Calculation.columns) :
                    mysql_list.append(Calculation[i])

                #print(mysql_list)
                # data table overview

                df_OV = pd.Series(OV, name='Info')
                df_OV.index.name = 'Data'
                list_header_OV = df_OV.index.tolist()
                #print (df_OV.head(5))

                db = connect("newstockmarket")
                cursor = db.cursor()

                #--------------------------------------------------------------------------------------------------------------------------------------------------
                ftable = "stock_fundamental"
                ovtable = "stock_overview"
                fintable = "financial_report"
                cashtable = "cashflow"
                incometable = "income_statement"
                balancetable = "balance_sheet"

                create_ovtable = ("CREATE TABLE IF NOT EXISTS {table} "
                                  #" ( Stock_ID int(5) NOT NULL AUTO_INCREMENT PRIMARY KEY, "
                                  " ( SYMBOL VARCHAR(8) NOT NULL PRIMARY KEY, ASSET_TYPE VARCHAR(30), NAME VARCHAR(50) NOT NULL, "
                                  " DESCRIPTION VARCHAR(255), EXCHANGE VARCHAR(10), CURRENCY VARCHAR(5), "
                                  " COUNTRY VARCHAR(50), SECTOR VARCHAR(50), INDUSTRY VARCHAR(50), "
                                  " ADDRESS VARCHAR(255), Full_Time_Employees INT(20), Fiscal_Year_End VARCHAR(15), "
                                  " LATEST_QUARTER DATE, DividendDate DATE, ExDividendDate DATE, "
                                  " LastSplitFactor DECIMAL(5,2), LastSplitDate DATE )"
                                 )
                create_fintable = ("CREATE TABLE IF NOT EXISTS {table} "
                                  " ( NUMBER int(5) NOT NULL AUTO_INCREMENT PRIMARY KEY, "
                                  " SYMBOL VARCHAR(8), MARKET_CAP DECIMAL(15,2), EBITDA DECIMAL(15,2), "
                                  " PER DECIMAL(15,2), PEGR DECIMAL(15,2), BOOK_VALUE DECIMAL(15,2), "
                                  " Dividend_Per_Share DECIMAL(15,2), Dividend_Yield DECIMAL(15,2), EPS DECIMAL(15,2), "
                                  " Revenue_Per_Share_TTM DECIMAL(15,2), Profit_Margin DECIMAL(15,2), Operating_Margin_TTM DECIMAL(15,2), "
                                  " ROA_TTM DECIMAL(15,2), ROE_TTM DECIMAL(15,2), REVENUE_TTM DECIMAL(15,2), "
                                  " Gross_Profit_TTM DECIMAL(15,2), Diluted_EPS_TTM DECIMAL(15,2), Quarterly_Earnings_Growth_YOY DECIMAL(15,2), "
                                  " Quarterly_Revenue_Growth_YOY DECIMAL(15,2), Analyst_Target_Price DECIMAL(15,2), Trailing_PE DECIMAL(15,2), "
                                  " Forward_PE DECIMAL(15,2), Price_to_Sales_Ratio_TTM DECIMAL(15,2), PBV DECIMAL(15,2), "
                                  " EVtoRevenue DECIMAL(15,2), EVtoEBITDA DECIMAL(15,2), Beta DECIMAL(15,2), "
                                  " 52WeekHigh DECIMAL(15,2), 52WeekLow DECIMAL(15,2), 50DayMovingAverage DECIMAL(15,2), "
                                  " 200DayMovingAverage DECIMAL(15,2), SharesOutstanding DECIMAL(15,2), SharesFloat DECIMAL(15,2), " 
                                  " SharesShort DECIMAL(15,2), SharesShortPriorMonth DECIMAL(15,2), ShortRatio DECIMAL(15,2), " 
                                  " ShortPercentOutstanding DECIMAL(15,2), ShortPercentFloat DECIMAL(15,2), PercentInsiders DECIMAL(15,2), "
                                  " PercentInstitutions DECIMAL(15,2), ForwardAnnualDividendRate DECIMAL(15,2), ForwardAnnualDividendYield DECIMAL(15,2), " 
                                  " PayoutRatio DECIMAL(15,2) ) "
                                  )
                create_ftable = ("CREATE TABLE IF NOT EXISTS {table} "
                               " ( UNIQUE_ID VARCHAR(20) NOT NULL PRIMARY KEY, SYMBOL VARCHAR(8) NOT NULL, "
                               " DATE date NOT NULL, LAST_PRICE_RP decimal(8, 2) NOT NULL,"
                               " SHARE_OUT decimal(15, 2) NOT NULL, MARKET_CAP_RP decimal(15, 2) NOT NULL, "
                               " DEVIDEN_RP decimal(15, 2) NOT NULL,  EPSTTMM_RP decimal(15, 2) NOT NULL, "
                               " PER_X decimal(15, 2) NOT NULL, BVPS_RP decimal(15, 2) NOT NULL, "
                               " PBV_X decimal(15, 2) NOT NULL, ROA_PERCENT decimal(15, 2) NOT NULL, "
                               " ROE_PERCENT decimal(15, 2) NOT NULL, EV decimal(15, 2) NOT NULL, "
                               " EBITDA decimal(15, 2) NOT NULL, EV_EBITDA_RATIO decimal(15, 2) NOT NULL, "
                               " D_E_RATIO decimal(15, 2) NOT NULL, DEBT_TOTALCAP_RATIO decimal(15, 2) NOT NULL, "
                               " DEBT_EBITDA_RATIO decimal(15, 2) NOT NULL) "
                               )

                create_cashtable = ("CREATE TABLE IF NOT EXISTS {table} "
                                    " ( uniqueId VARCHAR(20) NOT NULL PRIMARY KEY, symbol VARCHAR(8) NOT NULL, "
                                    " fiscaldate date NOT NULL, reportedCurrency VARCHAR(5), operatingCashflow decimal(15, 2) NOT NULL,"
                                    " paymentsForOperatingActivities decimal(15, 2) NOT NULL, proceedsFromOperatingActivities decimal(15, 2) NOT NULL, changeInOperatingLiabilities decimal(15, 2), "
                                    " changeInOperatingAssets decimal(15, 2) NOT NULL, depreciationDepletionAndAmortization decimal(15, 2) NOT NULL, capitalExpenditures decimal(15, 2), "
                                    " changeInReceivables decimal(15, 2), changeInInventory decimal(15, 2) NOT NULL, profitLoss decimal(15, 2), "
                                    " cashflowFromInvestment decimal(15, 2), cashflowFromFinancing decimal(15, 2), proceedsFromRepaymentsOfShortTermDebt decimal(15, 2), "
                                    " paymentsForRepurchaseOfCommonStock decimal(15, 2), paymentsForRepurchaseOfEquity decimal(15, 2), paymentsForRepurchaseOfPreferredStock decimal(15, 2), "
                                    " dividendPayout decimal(15, 2), dividendPayoutCommonStock decimal(15, 2), dividendPayoutPreferredStock decimal(15, 2), "
                                    " proceedsFromIssuanceOfCommonStock decimal(15, 2), proceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet decimal(15, 2), proceedsFromIssuanceOfPreferredStock decimal(15, 2), "
                                    " proceedsFromRepurchaseOfEquity decimal(15, 2), proceedsFromSaleOfTreasuryStock decimal(15, 2), changeInCashAndCashEquivalents decimal(15, 2), "
                                    " changeInExchangeRate decimal(15, 2), netIncome decimal(15, 2) )"
                                   )
                create_incometable = ("CREATE TABLE IF NOT EXISTS {table} "
                                      " ( uniqueId VARCHAR(20) NOT NULL PRIMARY KEY, symbol VARCHAR(8) NOT NULL, "
                                      " fiscaldate date NOT NULL, reportedCurrency VARCHAR(5), grossProfit decimal(15, 2) NOT NULL, "
                                      " totalRevenue decimal(15, 2) NOT NULL, costOfRevenue decimal(15, 2) NOT NULL,  costofGoodsAndServicesSold decimal(15, 2) NOT NULL, "
                                      " operatingIncome decimal(15, 2), sellingGeneralAndAdministrative decimal(15, 2), researchAndDevelopment decimal(15, 2), "
                                      " operatingExpenses decimal(15, 2), investmentIncomeNet decimal(15, 2), netInterestIncome decimal(15, 2), "
                                      " interestIncome decimal(15, 2), interestExpense decimal(15, 2), nonInterestIncome decimal(15, 2), "
                                      " otherNonOperatingIncome decimal(15, 2), depreciation decimal(15, 2), depreciationAndAmortization decimal(15, 2), "
                                      " incomeBeforeTax decimal(15, 2), incomeTaxExpense decimal(15, 2), interestAndDebtExpense decimal(15, 2), "
                                      " netIncomeFromContinuingOperations decimal(15, 2), comprehensiveIncomeNetOfTax decimal(15, 2), ebit decimal(15, 2), "
                                      " ebitda decimal(15, 2), netIncome decimal(15, 2) )"
                                    )       
                create_balancetable = ("CREATE TABLE IF NOT EXISTS {table} "
                                       " ( uniqueId VARCHAR(20) NOT NULL PRIMARY KEY, symbol VARCHAR(8) NOT NULL, "
                                       " fiscaldate date NOT NULL, reportedCurrency VARCHAR(5), totalAssets decimal(15, 2) NOT NULL, "
                                       " totalCurrentAssets decimal(15, 2), cashAndCashEquivalentsAtCarryingValue decimal(15, 2), cashAndShortTermInvestments decimal(15, 2), "
                                       " inventory decimal(15, 2), currentNetReceivables decimal(15, 2), totalNonCurrentAssets decimal(15, 2), "
                                       " propertyPlantEquipment decimal(15, 2), accumulatedDepreciationAmortizationPPE decimal(15, 2), intangibleAssets decimal(15, 2), "
                                       " intangibleAssetsExcludingGoodwill decimal(15, 2), goodwill decimal(15, 2), investments decimal(15, 2), "
                                       " longTermInvestments decimal(15, 2), shortTermInvestments decimal(15, 2), otherCurrentAssets decimal(15, 2), "
                                       " otherNonCurrrentAssets decimal(15, 2), totalLiabilities decimal(15, 2), totalCurrentLiabilities decimal(15, 2), "
                                       " currentAccountsPayable decimal(15, 2), deferredRevenue decimal(15, 2), currentDebt decimal(15, 2), "
                                       " shortTermDebt decimal(15, 2), totalNonCurrentLiabilities decimal(15, 2), capitalLeaseObligations decimal(15, 2), "
                                       " longTermDebt decimal(15, 2), currentLongTermDebt decimal(15, 2), longTermDebtNoncurrent decimal(15, 2), "
                                       " shortLongTermDebtTotal decimal(15, 2), otherCurrentLiabilities decimal(15, 2), otherNonCurrentLiabilities decimal(15, 2), "
                                       " totalShareholderEquity decimal(15, 2), treasuryStock decimal(15, 2), retainedEarnings decimal(15, 2), "
                                       " commonStock decimal(15, 2), commonStockSharesOutstanding decimal(15, 2) ) "
                                      )
            
                cursor = db.cursor()
                cursor.execute(create_ovtable.format(table=ovtable) )                    
                cursor.execute(create_fintable.format(table=fintable) )                
                cursor.execute(create_ftable.format(table=ftable) )
                cursor.execute(create_cashtable.format(table=cashtable) )                    
                cursor.execute(create_incometable.format(table=incometable) )                
                cursor.execute(create_balancetable.format(table=balancetable) )

                #------------------------------------------------------------------------------------------
                #inserting data overview into mysql
                insert_ovtable = ("INSERT IGNORE INTO {table} "
                                "( SYMBOL, ASSET_TYPE, "
                                "NAME, DESCRIPTION, EXCHANGE, "
                                "CURRENCY, COUNTRY, SECTOR, "
                                "INDUSTRY, ADDRESS, Full_Time_Employees, "
                                "Fiscal_Year_End, LATEST_QUARTER, DividendDate, "
                                "ExDividendDate, LastSplitFactor, LastSplitDate ) "
                                "VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)"
                                 )
                temp_data = []

                for i in range(13) :
                    single_data = df_OV[list_header_OV[i]]
                    temp_data.append(single_data)
                for i in range(55, len(list_header_OV)) :
                    single_data = df_OV[list_header_OV[i]]
                    temp_data.append(single_data)
                cursor.execute(insert_ovtable.format(table=ovtable), temp_data)
                
                ##############################
                #inserting financial report into mysql
                insert_fintable = ("INSERT IGNORE INTO {table} "
                                    "( SYMBOL, MARKET_CAP, EBITDA, " 
                                    " PER, PEGR, BOOK_VALUE, "
                                    " Dividend_Per_Share, Dividend_Yield, EPS, "
                                    " Revenue_Per_Share_TTM, Profit_Margin, Operating_Margin_TTM, "
                                    " ROA_TTM, ROE_TTM, REVENUE_TTM, "
                                    " Gross_Profit_TTM, Diluted_EPS_TTM, Quarterly_Earnings_Growth_YOY, "
                                    " Quarterly_Revenue_Growth_YOY, Analyst_Target_Price, Trailing_PE, "
                                    " Forward_PE, Price_to_Sales_Ratio_TTM, PBV, "
                                    " EVtoRevenue, EVtoEBITDA, Beta, "
                                    " 52WeekHigh, 52WeekLow, 50DayMovingAverage, "
                                    " 200DayMovingAverage, SharesOutstanding, SharesFloat, "
                                    " SharesShort, SharesShortPriorMonth, ShortRatio, "
                                    " ShortPercentOutstanding, ShortPercentFloat, PercentInsiders, "
                                    " PercentInstitutions, ForwardAnnualDividendRate, ForwardAnnualDividendYield, PayoutRatio ) "
                                    " VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, "
                                    " %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, "
                                    " %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s )"
                                  )
                temp_data = []
                temp_data.append(entity)
                for i in range(14, 56) :
                    single_data = df_OV[list_header_OV[i]]
                    temp_data.append(single_data)
                cursor.execute(insert_fintable.format(table=fintable), temp_data)

                #inserting data fundamental into mysql
                insert_ftable = ("INSERT IGNORE INTO {table} "
                               "(UNIQUE_ID, SYMBOL, DATE, LAST_PRICE_RP, SHARE_OUT, MARKET_CAP_RP, "
                               "DEVIDEN_RP, EPSTTMM_RP, PER_X, BVPS_RP, PBV_X, ROA_PERCENT, ROE_PERCENT, "
                               "EV, EBITDA, EV_EBITDA_RATIO, D_E_RATIO, DEBT_TOTALCAP_RATIO, "
                               "DEBT_EBITDA_RATIO) "
                               "VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)")
                j = 0
                while j < len(mysql_list[0]) :
                    temp_data = []
                    i = 0
                    while i < len(mysql_list) :
                        temp_data.append(str (mysql_list[i][j]))
                        #print(project_data)
                        i += 1

                    cursor.execute(insert_ftable.format(table=ftable), temp_data)
                    j += 1
                    
                ##############################    
                #dataframe to list
                cashtable_list = []
                Unique_ID  = []
                StockName = []
                StockName  = [entity.upper()]*len (CFQ_reader["fiscalDateEnding"]) 

                for i in range (len (CFQ_reader["fiscalDateEnding"]) ) :
                    temp = entity + str(CFQ_reader["fiscalDateEnding"][i].strftime('%Y%m%d'))
                    Unique_ID.append(temp)
                    i += 1

                cashtable_list.append(Unique_ID)
                cashtable_list.append(StockName)

                for i in list(CFQ_reader.columns) :
                    cashtable_list.append(CFQ_reader[i])  
                    
                #inserting data cash flow into mysql
                insert_cashtable = ("INSERT IGNORE INTO {table} "
                                    " ( uniqueId, symbol, "
                                    " fiscalDate, reportedCurrency, operatingCashflow, "
                                    " paymentsForOperatingActivities, proceedsFromOperatingActivities, changeInOperatingLiabilities, "
                                    " changeInOperatingAssets, depreciationDepletionAndAmortization, capitalExpenditures, "
                                    " changeInReceivables, changeInInventory, profitLoss, "
                                    " cashflowFromInvestment, cashflowFromFinancing, proceedsFromRepaymentsOfShortTermDebt, "
                                    " paymentsForRepurchaseOfCommonStock, paymentsForRepurchaseOfEquity, paymentsForRepurchaseOfPreferredStock, "
                                    " dividendPayout, dividendPayoutCommonStock, dividendPayoutPreferredStock, "
                                    " proceedsFromIssuanceOfCommonStock, proceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet, proceedsFromIssuanceOfPreferredStock, "
                                    " proceedsFromRepurchaseOfEquity, proceedsFromSaleOfTreasuryStock, changeInCashAndCashEquivalents, "
                                    " changeInExchangeRate, netIncome ) "
                                    " VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)" )             
                
                #inserting to mysql
                j = 0
                while j < len(cashtable_list[0]) :
                    temp_data = []
                    i = 0
                    while i < len(cashtable_list) :
                        temp_data.append(str (cashtable_list[i][j]))
                        #print(project_data)
                        i += 1

                    cursor.execute(insert_cashtable.format(table=cashtable), temp_data)
                    j += 1
                ##############################
                #dataframe to list
                incometable_list = []
                Unique_ID  = []
                StockName = []
                StockName  = [entity.upper()]*len (ISQ_reader["fiscalDateEnding"]) 

                for i in range (len (ISQ_reader["fiscalDateEnding"]) ) :
                    temp = entity + str(ISQ_reader["fiscalDateEnding"][i].strftime('%Y%m%d'))
                    Unique_ID.append(temp)
                    i += 1

                incometable_list.append(Unique_ID)
                incometable_list.append(StockName)

                for i in list(ISQ_reader.columns) :
                    incometable_list.append(ISQ_reader[i])  
                    
                #inserting incometable into mysql
                insert_incometable = ("INSERT IGNORE INTO {table} "
                                      " ( uniqueId, symbol, "
                                      " fiscalDate, reportedCurrency, grossProfit, "
                                      " totalRevenue, costOfRevenue, costofGoodsAndServicesSold, "
                                      " operatingIncome, sellingGeneralAndAdministrative, researchAndDevelopment, "
                                      " operatingExpenses, investmentIncomeNet, netInterestIncome, "
                                      " interestIncome, interestExpense, nonInterestIncome, "
                                      " otherNonOperatingIncome, depreciation, depreciationAndAmortization, "
                                      " incomeBeforeTax, incomeTaxExpense, interestAndDebtExpense, "
                                      " netIncomeFromContinuingOperations, comprehensiveIncomeNetOfTax, ebit, "
                                      " ebitda, netIncome ) "
                                      " VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)" )
                
                #inserting to mysql
                j = 0
                while j < len(incometable_list[0]) :
                    temp_data = []
                    i = 0
                    while i < len(incometable_list) :
                        temp_data.append(str (incometable_list[i][j]))
                        #print(project_data)
                        i += 1

                    cursor.execute(insert_incometable.format(table=incometable), temp_data)
                    j += 1
                
                ##############################
                #dataframe to list
                balancetable_list = []
                Unique_ID  = []
                StockName = []
                StockName  = [entity.upper()]*len (BSQ_reader["fiscalDateEnding"]) 

                for i in range (len (BSQ_reader["fiscalDateEnding"]) ) :
                    temp = entity + str(BSQ_reader["fiscalDateEnding"][i].strftime('%Y%m%d'))
                    Unique_ID.append(temp)
                    i += 1

                balancetable_list.append(Unique_ID)
                balancetable_list.append(StockName)

                for i in list(BSQ_reader.columns) :
                    balancetable_list.append(BSQ_reader[i])  
                    
                #inserting incometable into mysql
                insert_balancetable = ("INSERT IGNORE INTO {table} "
                                        " ( uniqueId, symbol, "
                                        " fiscalDate, reportedCurrency, totalAssets, "
                                        " totalCurrentAssets, cashAndCashEquivalentsAtCarryingValue, cashAndShortTermInvestments, "
                                        " inventory, currentNetReceivables, totalNonCurrentAssets, "
                                        " propertyPlantEquipment, accumulatedDepreciationAmortizationPPE, intangibleAssets, "
                                        " intangibleAssetsExcludingGoodwill, goodwill, investments, "
                                        " longTermInvestments, shortTermInvestments, otherCurrentAssets, "
                                        " otherNonCurrrentAssets, totalLiabilities, totalCurrentLiabilities, "
                                        " currentAccountsPayable, deferredRevenue, currentDebt, "
                                        " shortTermDebt, totalNonCurrentLiabilities, capitalLeaseObligations, "
                                        " longTermDebt, currentLongTermDebt, longTermDebtNoncurrent, "
                                        " shortLongTermDebtTotal, otherCurrentLiabilities, otherNonCurrentLiabilities, "
                                        " totalShareholderEquity, treasuryStock, retainedEarnings, "
                                        " commonStock, commonStockSharesOutstanding ) "
                                        " VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, "
                                        " %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)" )

                #inserting to mysql
                j = 0
                while j < len(balancetable_list[0]) :
                    temp_data = []
                    i = 0
                    while i < len(balancetable_list) :
                        temp_data.append(str (balancetable_list[i][j]))
                        #print(project_data)
                        i += 1
                    cursor.execute(insert_balancetable.format(table=balancetable), temp_data)
                    j += 1
                    
                    
                db.commit()
                db.close()
                time.sleep(10)
                break
            except ValueError as e :
                print (e)
                if str(e) == "Error getting data from the api, no return was given." :
                    print ("Problem Ticker Name : "+entity+" ...Skipping")
                    break
                    continue

                else :
                    if (step == "step_2") :
                        procedure = [step_2,step_3,step_4,step_5]
                        print ("beginning from step 2")
                        randomize()
                        time.sleep(10)  
                    elif (step == "step_3") :
                        procedure = [step_3,step_4,step_5]
                        print ("beginning from step 3")
                        randomize()
                        time.sleep(10)  
                    elif (step == "step_4") :
                        procedure = [step_4,step_5]
                        print ("beginning from step 4")
                        randomize()
                        time.sleep(10) 
                    elif (step == "step_5") :
                        procedure = [step_5]
                        print ("beginning from step 5")
                        randomize()
                        time.sleep(10)  
                    else :
                        print ("Step 1 Problem API Limit..Try Again")
                        print (step)
                        randomize()
                        time.sleep(10)        
#     except ValueError :
#         time.sleep(5)
#         continue
        
#######################################################################################################################################################################################################################################################################################################

Creation of the directory /Varians failed
Stock Ticker Name : DPSGY
the API key right now is : 6PE06AMZAM1MCGFX
Thank you for using Alpha Vantage! Our standard API call frequency is 5 calls per minute and 500 calls per day. Please visit https://www.alphavantage.co/premium/ if you would like to target a higher API call frequency.
Step 1 Problem API Limit..Try Again
step_1
the API key right now is : 6HZYCBP71FGOR1O5
Thank you for using Alpha Vantage! Our standard API call frequency is 5 calls per minute and 500 calls per day. Please visit https://www.alphavantage.co/premium/ if you would like to target a higher API call frequency.
Step 1 Problem API Limit..Try Again
step_1
the API key right now is : X5LNMI2AESR1YQCU
Thank you for using Alpha Vantage! Our standard API call frequency is 5 calls per minute and 500 calls per day. Please visit https://www.alphavantage.co/premium/ if you would like to target a higher API call frequency.
Step 1 Problem API Limit..Try Again
step_1
the API key right now is : YBBKWRK4VSTP4GZH
Error getting data from the api, no return was given.
Problem Ticker Name : DPSGY ...Skipping
Stock Ticker Name : UPS
the API key right now is : 6PE06AMZAM1MCGFX
Succsesfully Pull Data 1 from web
Succsesfully Pull Data 2 from web
Succsesfully Pull Data 3 from web
Succsesfully Pull Data Overview from web
Thank you for using Alpha Vantage! Our standard API call frequency is 5 calls per minute and 500 calls per day. Please visit https://www.alphavantage.co/premium/ if you would like to target a higher API call frequency.
beginning from step 5
the API key right now is : 6HZYCBP71FGOR1O5
Thank you for using Alpha Vantage! Our standard API call frequency is 5 calls per minute and 500 calls per day. Please visit https://www.alphavantage.co/premium/ if you would like to target a higher API call frequency.
beginning from step 5
the API key right now is : X5LNMI2AESR1YQCU
Thank you for using Alpha Vantage! Our standard API call frequency is 5 calls per minute and 500 calls per day. Please visit https://www.alphavantage.co/premium/ if you would like to target a higher API call frequency.
beginning from step 5
the API key right now is : YBBKWRK4VSTP4GZH
Thank you for using Alpha Vantage! Our standard API call frequency is 5 calls per minute and 500 calls per day. Please visit https://www.alphavantage.co/premium/ if you would like to target a higher API call frequency.
beginning from step 5
the API key right now is : X3Z3LQ31Z9B1OYX9
Succsesfully Pull Data Timeseries from web
Date             datetime64[ns]
LastPrice               float64
ShareOut                float64
MarketCap               float64
EPS                     float64
EPSTTM                  float64
PER                     float64
BVPS                    float64
PBV                     float64
ROA%                    float64
ROE%                    float64
EV                      float64
EBITDA                  float64
EV/EBITDA               float64
D/E                     float64
Debt/Totalcap           float64
Debt/EBITDA             float64
dtype: object
Stock Ticker Name : XPO
the API key right now is : 6PE06AMZAM1MCGFX
Succsesfully Pull Data 1 from web
Succsesfully Pull Data 2 from web
Succsesfully Pull Data 3 from web
Succsesfully Pull Data Overview from web
Thank you for using Alpha Vantage! Our standard API call frequency is 5 calls per minute and 500 calls per day. Please visit https://www.alphavantage.co/premium/ if you would like to target a higher API call frequency.
beginning from step 5
the API key right now is : 6HZYCBP71FGOR1O5
Thank you for using Alpha Vantage! Our standard API call frequency is 5 calls per minute and 500 calls per day. Please visit https://www.alphavantage.co/premium/ if you would like to target a higher API call frequency.
beginning from step 5
the API key right now is : X5LNMI2AESR1YQCU
Thank you for using Alpha Vantage! Our standard API call frequency is 5 calls per minute and 500 calls per day. Please visit https://www.alphavantage.co/premium/ if you would like to target a higher API call frequency.
beginning from step 5
the API key right now is : YBBKWRK4VSTP4GZH
Succsesfully Pull Data Timeseries from web
Date             datetime64[ns]
LastPrice               float64
ShareOut                float64
MarketCap               float64
EPS                     float64
EPSTTM                  float64
PER                     float64
BVPS                    float64
PBV                     float64
ROA%                    float64
ROE%                    float64
EV                      float64
EBITDA                  float64
EV/EBITDA               float64
D/E                     float64
Debt/Totalcap           float64
Debt/EBITDA             float64
dtype: object
Stock Ticker Name : JBHT
the API key right now is : 6PE06AMZAM1MCGFX
Succsesfully Pull Data 1 from web
Succsesfully Pull Data 2 from web
Succsesfully Pull Data 3 from web
Succsesfully Pull Data Overview from web
Thank you for using Alpha Vantage! Our standard API call frequency is 5 calls per minute and 500 calls per day. Please visit https://www.alphavantage.co/premium/ if you would like to target a higher API call frequency.
beginning from step 5
the API key right now is : 6HZYCBP71FGOR1O5

KeyboardInterrupt: